[build]
  base = "."
  publish = "public/"
  command = "npm run build"

[build.environment]
  STORYBLOK_TOKEN = "Enter your Storyblok API key here 3"

[context.production.environment]
  STORYBLOK_TOKEN = "Enter your Storyblok API key here 1"

#[context.production]
#  environment = { STORYBLOK_TOKEN = "Enter your Storyblok API key here 2"}